# Generated by Django 4.1.2 on 2022-10-21 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profileuser",
            old_name="image",
            new_name="profile_image",
        ),
    ]
