# Generated by Django 4.1.2 on 2022-10-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_rename_image_profileuser_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileuser",
            name="address",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profileuser",
            name="company_name",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profileuser",
            name="state",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="profileuser",
            name="zip_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profileuser",
            name="profile_image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="profile_pics"
            ),
        ),
    ]
